### ISSUE TITLE
WritingTool crashes - 2024-08-06

### ISSUE THREAD

**Issue by marcoagpinto** [FredKruse/writingtool#10]
Heya, @FredKruse 

The latest nightly crashes and the date shown in the crash window is from 4-AUG instead of 5-AUG.

![Screenshot 2024-08-06 064506](https://github.com/user-attachments/assets/f45e213a-05ff-4245-aade-5a61c2edb2a9)

EDIT:
Version: 24.8.0.2 (X86_64) / LibreOffice Community
Build ID: 57ceca7d2eefdf83e7c9b4135a017f3361a8133f
CPU threads: 12; OS: Windows 11 X86_64 (10.0 build 22631); UI render: Skia/Raster; VCL: win
Locale: pt-PT (pt_PT); UI: en-GB
Calc: CL threaded

**Comment by FredKruse** [comment]
The null pointer exception is solved in the current nightly. The switch to WritingTool (inclusive build date) will be solved in tomorrows nightly.
