### ISSUE TITLE
Snapshot 20240818 does not install; extension does not work

### ISSUE THREAD

**Issue by GerryT11** [FredKruse/writingtool#12]
Snapshot 20240818 does not install properly. I get the following error message.

System: Ubuntu 24.04, LibreOffice 24.2
![Screenshot from 2024-08-19 13-42-58](https://github.com/user-attachments/assets/c8f2ebae-5d11-4eb4-a100-320a10f1d838)

**Edit**: The error message appears not only at the time of installation of the extension, but at every start of LibreOffice. As a consequence of the error message, WritingTool does not work.

**Edit 2**: I did some further testing. The snapshot from the 12 August 2024 "WritingTool_2024-08-12-snapshot.oxt" still works fine, but all later snapshots fail to install and don't work. All of the following snapshots (which I tested) don't work: Aug 13, Aug 14, Aug 18, Aug 19. Thus, I assume that there is a regression in the versions after August 12.

**Comment by FredKruse** [comment]
The issue should be solved. Please try it with tomorrow's snapshot.

**Comment by GerryT11** [comment]
Thanks, I will try.

**Comment by GerryT11** [comment]
Snapshot 20240901 fixed the bug. No error message and WritingTool works perfectly.
