### ISSUE TITLE
“Prefer longer suggestions” ("messages"?)

### ISSUE THREAD

**Issue by marcoagpinto** [FredKruse/writingtool#13]
Heya, @FredKruse ,

Could you add a checkbox (that should be on by default) with the name in the title?

For example (pt-PT):
`Outra forma de verificar se os dispositivos funcionam seria usá-los por um longo período, uns 10–15 anos, até termos 40+ anos e olhar-nos ao espelho para ver se parecemos estar na casa dos 20. Mas as duas formas mencionadas acima são mais praticáveis.`

It shows (prefers) the short message, which isn't helpful:
![coloquialismo](https://github.com/user-attachments/assets/4405a2e2-f177-4bb6-b9e5-6781e41347b5)

```
    <rule>
        <pattern>
            <token>para</token>
            <token inflected='yes'>ver</token>
            <token>se</token>
        </pattern>
        <message>Esta é uma expressão oral. Reveja.</message>
        <short>Coloquialismo</short>
        <example correction=''><marker>para ver se</marker></example>
    </rule>
```

Thanks!

**Comment by FredKruse** [comment]
Hey @marcoagpinto,
Technically, this is not a problem. However, we should briefly consider together whether it makes sense. The LO add-on behaves in such a way that the short message is used first. If there is no short message, the long one is used (it is shortened to a maximum of 100 characters).
As far as I know, this is the case in all LanguageTool add-ons.
It is therefore worth considering whether a meaningless short message makes any sense at all, or whether it should be omitted from the rule.
Can you check how your example is displayed in other LT applications?

**Comment by FredKruse** [comment]
I just did some tests. In Thunderbird, it works the same way as in LO.
If we introduce such a switch, it should not be the default.

**Comment by marcoagpinto** [comment]
> I just did some tests. In Thunderbird, it works the same way as in LO. If we introduce such a switch, it should not be the default.

Sure, but is it doable?

Thanks!

**Comment by FredKruse** [comment]
The issue should be solved. Please test it with tomorrows nightly.

**Comment by marcoagpinto** [comment]
Thanks, @FredKruse

**Comment by marcoagpinto** [comment]
It is working!!!!

Thanks!
