### ISSUE TITLE
No https in snapshots site

### ISSUE THREAD

**Issue by marcoagpinto** [FredKruse/writingtool#2]
Heya, @FredKruse 

Thank you for all your amazing work and efforts.

I went to:
fred-kruse.de/writingtool/snapshots/
and the connection is not https.

Is it possible that you use Let's Encript SSL there? It is free and powerful.

**Comment by FredKruse** [comment]
The snapshot directory has changed. It now supports HTTPS and is now located here: [Index of /writingtool/snapshots](https://fk-es.de/writingtool/snapshots/)

**Comment by marcoagpinto** [comment]
It is working, thanks!
