### ISSUE TITLE
[pt-PT] Allow pre- and -post language agreement — 2024-07-21

### ISSUE THREAD

**Issue by marcoagpinto** [FredKruse/writingtool#6]
Heya, @FredKruse ,

Could this feature be implemented?

![pt-pt_20240721](https://github.com/user-attachments/assets/24ee055d-0d04-43cb-8e6f-ba06df1f4af2)

“AO” means “Acordo Ortográfico” (“Orthographic Agreement”) and we have the one from 1945 (before the agreement) and the one from 1990 (after the agreement).

My idea is this:
o AO1945
1. Disable category:   
`<category id="AO90_RULES_PT_PT" name="[pt-PT] Regras do Acordo Ortográfico de 90 (pós-AO90)" type="misspelling" default='on'>`
2. Enable category:
`<category id="AO45_RULES_PT_PT" name="[pt-PT][AO45] Regras do Acordo Ortográfico de 45 (pré-AO90)" type="misspelling" default='off'>`
3. Enable dictionary:
`pt_PT_45.aff + pt_PT_45.dic`

o AO1990 (default)
1. Enable category:   
`<category id="AO90_RULES_PT_PT" name="[pt-PT] Regras do Acordo Ortográfico de 90 (pós-AO90)" type="misspelling" default='on'>`
2. Disable category:
`<category id="AO45_RULES_PT_PT" name="[pt-PT][AO45] Regras do Acordo Ortográfico de 45 (pré-AO90)" type="misspelling" default='off'>`
3. Enable dictionary:
`pt_PT_90.aff + pt_PT_90.dic`

Is it doable?

Thanks!

**Comment by FredKruse** [comment]
The activation/deactivation of categories can be controlled via the extension. Switching between different dictionaries is a matter for the LanguageTool core.
I think it would be easier if you defined two language variants (old/new variant), which can then be switched via the option dialog.

**Comment by marcoagpinto** [comment]
Heya, @FredKruse ,

I am confused. Is it possible for you to toggle both dictionaries (AO45 and AO90) from the extension?

Thanks!
