### ISSUE TITLE
WritingTool error message

### ISSUE THREAD

**Issue by GerryT11** [FredKruse/writingtool#7]
Using WritingTool I got the following error message.

![WritingTool-ErrorMessage](https://github.com/user-attachments/assets/3f0c9b15-845c-47ba-981f-f3176d709678)

System: Ubuntu 24.02, LibreOffice 24.2, WritingTool Snapshot 2024-07-05

**Comment by FredKruse** [comment]
@GerryT11, I can't reproduce the error.
Do you have a file where the error can be reproduced?
Did it occur when writing to the document?

**Comment by GerryT11** [comment]
Thank you for your response on the bug report.

The error message appeared while I was writing. I tried today to reproduce the error (with the same document), but I wasn't able to reproduce it myself.

What do you suggest to do the next time that I get an error message in WritingTool? What information do you need to find the cause of the error? Screenshot? A description of the exact situation when the error occurred? The document (if it is not confidential like this time)? Anything else which is helpful for you to trace the bug?

**Comment by FredKruse** [comment]
The issue should be solved with tomorrow nightly. Please report if it occurs again.

**Comment by GerryT11** [comment]
Thank you!

**Comment by GerryT11** [comment]
I mark this issue as solved. I'll reopen it if it occurs again.
